export const data = {
  foods: [
    {
      thumb: './assets/images/foods/frango_yin_yang 1.png',
      title: 'Frango Yin Yang',
      description: 'Um pouco de batata, um pouco de salada',
      price: 14.90,
      tags: '',
    },
    {
      thumb: 'assets/images/foods/abobora.jpg',
      title: 'Abóbora Deliciosa',
      description: 'Um pouco de abóbora, um pouco de carne',
      price: 9.90,
      tags: '',
    },
    {
      thumb: './assets/images/foods/aipim.webp',
      title: 'Escondidinho de Aipim',
      description: 'Um pratão de um delicioso esondidinho de aipim',
      price: 16.90,
      tags: '',
    },
    {
      thumb: './assets/images/foods/alface.webp',
      title: 'Alface Clean',
      description: 'Um pouco de alface, um pouco de tomate',
      price: 7.90,
      tags: '',
    },
    {
      thumb: './assets/images/foods/Escondidinho1.jpg',
      title: 'Escondidinho de Batata',
      description: 'Um pratão de um delicioso esondidinho de batata',
      price: 16.90,
      tags: '',
    },
    {
      thumb: './assets/images/foods/macarrao.webp',
      title: 'Macarrão Carbonara',
      description: 'Um macarrão carbonara delicioso',
      price: 14.90,
      tags: '',
    },
    {
      thumb: './assets/images/foods/peixe.webp',
      title: 'Peixe Clean',
      description: 'Um pouco de peixe, um pouco de salada',
      price: 9.90,
      tags: '',
    },
    {
      thumb: './assets/images/foods/puchero.webp',
      title: 'Puchero Top',
      description: 'Um puchero bem gostoso',
      price: 17.90,
      tags: '',
    },
    {
      thumb: './assets/images/foods/salada.jpg',
      title: 'Salada Clean',
      description: 'Um pratão de salada completo',
      price: 15.90,
      tags: '',
    },
    {
      thumb: './assets/images/foods/strog.jpeg',
      title: 'StrogoTop',
      description: 'Um Strognoff bem gostoso',
      price: 17.90,
      tags: '',
    },
  ],
  drinks: [
    {
      thumb: './assets/images/drinks/camp.png',
      title: 'GuaraCamp',
      description: 'Copo 285ml',
      tags: 'refri suco',
      price: 3.90,
    },
    {
      thumb: './assets/images/drinks/coquinha_gelada 1.png',
      title: 'Coquinha gelada',
      description: 'Lata 350ml',
      tags: 'refri',
      price: 4.90,
    },
    {
      thumb: './assets/images/drinks/fanta.jpeg',
      title: 'Fantags',
      description: 'Lata 350ml',
      tags: 'refri',
      price: 4.90,
    },
    {
      thumb: './assets/images/drinks/guaravita.jpeg',
      title: 'Guaravita',
      description: 'Lata 285ml',
      tags: 'refri',
      price: 3.90,
    },
    {
      thumb: './assets/images/drinks/jesus.jpg',
      title: 'Guaraná Jesus',
      description: 'Lata 350ml',
      tags: 'refri',
      price: 4.90,
    },
    {
      thumb: './assets/images/drinks/amstel.jpg',
      title: 'Cerveja Amstel',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/antartica.jpeg',
      title: 'Cerveja Antartica',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/becks.jpeg',
      title: 'Cerveja Becks',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 6.90,
    },
    {
      thumb: './assets/images/drinks/bohemia.jpg',
      title: 'Cerveja Bohemia',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 6.90,
    },
    {
      thumb: './assets/images/drinks/brama.jpg',
      title: 'Cerveja Brama',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 3.90,
    },
    {
      thumb: './assets/images/drinks/brancoBordegas.webp',
      title: 'Vinho Branco Bordegas',
      description: 'Garrafa 750ml',
      tags: 'vinho branco',
      price: 70.90,
    },
    {
      thumb: './assets/images/drinks/brancoDomBosco.webp',
      title: 'Vinho Branco Dom Bosco',
      description: 'Garrafa 750ml',
      tags: 'vinho branco',
      price: 50.90,
    },
    {
      thumb: './assets/images/drinks/brancoMontePaschoal.jpg',
      title: 'Vinho Branco Monte Paschoal',
      description: 'Garrafa 750ml',
      tags: 'vinho branco',
      price: 60.90,
    },
    {
      thumb: './assets/images/drinks/brussels.webp',
      title: 'Cerveja Brussels',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/budweiser.jpeg',
      title: 'Cerveja Budweiser',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 7.90,
    },
    {
      thumb: './assets/images/drinks/cachaca51.png',
      title: 'Cachaça 51',
      description: 'Garrafa 850ml',
      tags: 'cachaca',
      price: 25.90,
    },
    {
      thumb: './assets/images/drinks/cachacaBananinha.jpeg',
      title: 'Cachaça Bananinha',
      description: 'Lata 850ml',
      tags: 'cachaca',
      price: 15.90,
    },
    {
      thumb: './assets/images/drinks/cachacaCaranguejo.jpg',
      title: 'Cachaça Caranguejo',
      description: 'Lata 350ml',
      tags: 'cachaca',
      price: 8.90,
    },
    {
      thumb: './assets/images/drinks/cachacaSalinas.jpeg',
      title: 'Cachaça Salinas',
      description: 'Lata 750ml',
      tags: 'cachaca',
      price: 30.90,
    },
    {
      thumb: './assets/images/drinks/cacildis.jpg',
      title: 'Cerveja Cacildis',
      description: 'Lata 850ml',
      tags: 'cerveja',
      price: 15.90,
    },
    {
      thumb: './assets/images/drinks/colorado.png',
      title: 'Cerveja Colorado',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/corona.jpg',
      title: 'Cerveja Corona',
      description: 'Lata 750ml',
      tags: 'cerveja',
      price: 10.90,
    },
    {
      thumb: './assets/images/drinks/eisenbahn.jpg',
      title: 'Cerveja Eisenbahn',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/esmera.jpg',
      title: 'Cerveja Esmera',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/faxe.webp',
      title: 'Cerveja Faxe',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/garcia.webp',
      title: 'Cerveja Garcia',
      description: 'Lata 750ml',
      tags: 'cerveja',
      price: 12.90,
    },
    {
      thumb: './assets/images/drinks/glacial.jpg',
      title: 'Cerveja Glacial',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 3.90,
    },
    {
      thumb: './assets/images/drinks/heinekin.jpg',
      title: 'Cerveja Heineken',
      description: 'Garrafa 450ml',
      tags: 'cerveja',
      price: 8.90,
    },
    {
      thumb: './assets/images/drinks/pergola.webp',
      title: 'Vinho Tinto Pérgola',
      description: 'Garrafa 750ml',
      tags: 'vinho tinto',
      price: 10.90,
    },
    {
      thumb: './assets/images/drinks/imperio.webp',
      title: 'Cerveja Império',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/itaipava.webp',
      title: 'Cerveja Itaipava',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/kaiser.webp',
      title: 'Cerveja Kaiser',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/lokal.png',
      title: 'Cerveja Lokal',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/quilmes.jpeg',
      title: 'Cerveja Quilmes',
      description: 'Garrafa 750ml',
      tags: 'cerveja',
      price: 10.90,
    },
    {
      thumb: './assets/images/drinks/skol.webp',
      title: 'Cerveja Skol',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/stella.jpeg',
      title: 'Cerveja Stella',
      description: 'Garrafa 550ml',
      tags: 'cerveja',
      price: 8.90,
    },
    {
      thumb: './assets/images/drinks/tiger.jpg',
      title: 'Cerveja Tiger',
      description: 'Lata 350ml',
      tags: 'cerveja',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/tintoCampoLargo.jpg',
      title: 'Vinho Tinto Campo Largo',
      description: 'Garrafa 750ml',
      tags: 'vinho tinto',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/tintoPalato.webp',
      title: 'Vinho Tinto Palato',
      description: 'Garrafa 750ml',
      tags: 'vinho tinto',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/tintoSebrumo.png',
      title: 'Vinho Tinto Sebrumo',
      description: 'Garrafa 750ml',
      tags: 'vinho tinto',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/vodkaAbsolute.webp',
      title: 'Vodka Absolute',
      description: 'Garrafa 750ml',
      tags: 'vodka',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/vodkaOrloff.webp',
      title: 'Vodka Orloff',
      description: 'Garrafa 750ml',
      tags: 'vodka',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/vodkaSlova.webp',
      title: 'Vodka Slova',
      description: 'Garrafa 750ml',
      tags: 'vodka',
      price: 5.90,
    },
    {
      thumb: './assets/images/drinks/vodkaSmirnoff.webp',
      title: 'Vodka Smirnoff',
      description: 'Garrafa 350ml',
      tags: 'vodka',
      price: 5.90,
    },
  ],
  desserts: [
    {
      thumb: './assets/images/desserts/beijinho.jpg',
      title: 'Beijinho',
      description: '10 beijinhos deliciosos',
      tags: 'doce',
      price: 10.90,
    },
    {
      thumb: './assets/images/desserts/brigadeir.webp',
      title: 'Brigadeiro',
      description: '10 brigadeiros deliciosos',
      tags: 'doce',
      price: 11.90,
    },
    {
      thumb: './assets/images/desserts/coco.jpeg',
      title: 'Doce de coco',
      description: 'Doce de coco maravilhoso',
      tags: 'doce',
      price: 10.90,
    },
    {
      thumb: './assets/images/desserts/doceabobora.jpeg',
      title: 'Doce de Abóbora',
      description: 'Doce de abóbora maravilhoso',
      tags: 'doce',
      price: 10.90,
    },
    {
      thumb: './assets/images/desserts/bolobanana.jpeg',
      title: 'Bolo de Banana',
      description: 'Bolo de Banana Delicioso',
      price: 15.90,
      tags: 'bolo banana',
    },
    {
      thumb: './assets/images/desserts/boloCenoura.webp',
      title: 'Bolo de Cenoura Delicioso',
      description: 'Bolo de Cenoura Delicioso',
      price: 12.90,
      tags: 'bolo cenoura',
    },
    {
      thumb: './assets/images/desserts/boloChoco.jpg',
      title: 'Bolo de Chocolate',
      description: 'Bolo de Chocolate Delicioso',
      price: 10.90,
      tags: 'bolo chocolate',
    },
    {
      thumb: './assets/images/desserts/boloLaranja.png',
      title: 'Bolo de Laranja',
      description: 'Bolo de Laranja Delicioso',
      price: 9.90,
      tags: 'bolo laranja',
    },
    {
      thumb: './assets/images/desserts/boloMaca.jpeg',
      title: 'Bolo de Maçã',
      description: 'Bolo de Maçã Delicioso',
      price: 12.90,
      tags: 'bolo maca',
    },
    {
      thumb: './assets/images/desserts/boloMaracuja.jpg',
      title: 'Bolo de Maracujá',
      description: 'Bolo de Maracujá Delicioso',
      price: 15.90,
      tags: 'bolo maracuja',
    },
    {
      thumb: './assets/images/desserts/boloMilho.jpg',
      title: 'Bolo de Milho',
      description: 'Bolo de Banana Delicioso',
      price: 10.90,
      tags: 'bolo banana',
    },
    {
      thumb: './assets/images/desserts/boloMorango.webp',
      title: 'Bolo de Morango',
      description: 'Bolo de Morango Delicioso',
      price: 16.90,
      tags: 'bolo morango',
    },
    {
      thumb: './assets/images/desserts/doceAmendoim.jpg',
      title: 'Doce de Amendoim',
      description: 'Doce de Amendoim Delicioso',
      price: 7.90,
      tags: 'doce amendoim',
    },
    {
      thumb: './assets/images/desserts/doceBanana.webp',
      title: 'Doce de Banana',
      description: 'Milkshake de Delicioso',
      price: 7.90,
      tags: 'doce banana',
    },
    {
      thumb: './assets/images/desserts/doceDeCaju.jpg',
      title: 'Doce de Cajú',
      description: 'Doce de Cajú Delicioso',
      price: 7.90,
      tags: 'doce caju',
    },
    {
      thumb: './assets/images/desserts/doceDeLeite.jpeg',
      title: 'Doce de Leite',
      description: 'Doce de Leite Delicioso',
      price: 9.90,
      tags: 'doce leite',
    },
    {
      thumb: './assets/images/desserts/doceFigo.jpg',
      title: 'Doce de Figo',
      description: 'Doce de Figo Delicioso',
      price: 8.90,
      tags: 'doce figo',
    },
    {
      thumb: './assets/images/desserts/doceMamao.webp',
      title: 'Doce de Mamão',
      description: 'Doce de Mamão Delicioso',
      price: 7.90,
      tags: 'doce mamao',
    },
    {
      thumb: './assets/images/desserts/gelatinaLimao.webp',
      title: 'Gelatina de Limão',
      description: 'Gelatina de Mamão Delicioso',
      price: 8.90,
      tags: 'gelatina limao',
    },
    {
      thumb: './assets/images/desserts/gelatinaMorango.jpg',
      title: 'Gelatina de Morango',
      description: 'Gelatina de Morango Delicioso',
      price: 7.90,
      tags: 'gelatina morango',
    },
    {
      thumb: './assets/images/desserts/milkAcai.jpg',
      title: 'Milkshake de Açaí',
      description: 'Milkshake de Açaí Delicioso',
      price: 12.90,
      tags: 'milkshake acai',
    },
    {
      thumb: './assets/images/desserts/milkBacon.webp',
      title: 'Milkshake de Bacon',
      description: 'Milkshake de Bacon Delicioso',
      price: 15.90,
      tags: 'milkshake bacon',
    },
    {
      thumb: './assets/images/desserts/milkCafe.webp',
      title: 'Milkshake de Café',
      description: 'Milkshake de Café Delicioso',
      price: 10.90,
      tags: 'milkshake cafe',
    },
    {
      thumb: './assets/images/desserts/milkMorango.jpg',
      title: 'Milkshake de Morango',
      description: 'Milkshake de Morango Delicioso',
      price: 10.90,
      tags: 'milkshake morango',
    },
    {
      thumb: './assets/images/desserts/milkNut.jpeg',
      title: 'Milkshake de Nutella',
      description: 'Milkshake de Nutella Delicioso',
      price: 12.90,
      tags: 'milkshake nutella',
    },
    {
      thumb: './assets/images/desserts/milkOreo.jpeg',
      title: 'Milkshake de Óreo',
      description: 'Milkshake de Oréo Delicioso',
      price: 13.90,
      tags: 'milkshake oreo',
    },
    {
      thumb: './assets/images/desserts/milkPacoca.jpg',
      title: 'Milkshake de Paçoca',
      description: 'Milkshake de Paçoca Delicioso',
      price: 13.90,
      tags: 'milkshake pacoca',
    },
    {
      thumb: './assets/images/desserts/mousseChoco.jpg',
      title: 'Mousse de Chocolate',
      description: 'Mousse de chocolate Delicioso',
      price: 15.90,
      tags: 'mousse chocolate',
    },
    {
      thumb: './assets/images/desserts/mousseLimao.webp',
      title: 'Mousse de Limão',
      description: 'Mousse de Limão Delicioso',
      price: 14.90,
      tags: 'mousse limao',
    },
    {
      thumb: './assets/images/desserts/mousseMaracuja.jpg',
      title: 'Mousse de Maracujá',
      description: 'Mousse de Maracujá Delicioso',
      price: 13.90,
      tags: 'mousse maracuja',
    },
    {
      thumb: './assets/images/desserts/picleChoco.jpg',
      title: 'Picolé de Chocolate',
      description: 'Picolé de Delicioso',
      price: 7.90,
      tags: 'picole chocolate',
    },
    {
      thumb: './assets/images/desserts/picoleItu.jpeg',
      title: 'Picolé Itú',
      description: 'Picolé Itú Delicioso',
      price: 7.90,
      tags: 'picole itu',
    },
    {
      thumb: './assets/images/desserts/picoleMelancia.jpeg',
      title: 'Picolé de Melancia',
      description: 'Picolé de Melancia Delicioso',
      price: 7.90,
      tags: 'picole melancia',
    },
    {
      thumb: './assets/images/desserts/picoleMilhoverde.jpg',
      title: 'Picolé de Milho Verde',
      description: 'Picolé de Milho Verde Delicioso',
      price: 7.90,
      tags: 'picole milhoverde',
    },
    {
      thumb: './assets/images/desserts/picoleMorango.jpeg',
      title: 'Picolé de Morango',
      description: 'Picolé de Morango Delicioso',
      price: 7.90,
      tags: 'picole morango',
    },
    {
      thumb: './assets/images/desserts/pudimLimao.jpg',
      title: 'Pudim de Limão',
      description: 'Pudim de Limão Delicioso',
      price: 12.90,
      tags: 'pudim limao',
    },
    {
      thumb: './assets/images/desserts/pudimPao.webp',
      title: 'Pudim de Pão',
      description: 'Pudim de Pão Delicioso',
      price: 12.90,
      tags: 'pudim pao',
    },
    {
      thumb: './assets/images/desserts/pudimPassas.webp',
      title: 'Pudim de Passas',
      description: 'Pudim de Passas Delicioso',
      price: 12.90,
      tags: 'pudim passas',
    },
    {
      thumb: './assets/images/desserts/romeu.jpg',
      title: 'Doce Romeu e Julieta',
      description: 'Romeu e Julieta Delicioso',
      price: 7.90,
      tags: 'doce',
    },
    {
      thumb: './assets/images/desserts/sorveteBaunilha.jpg',
      title: 'Sorvete de Baunilha',
      description: 'Sorvete de Baunilha Delicioso',
      price: 9.90,
      tags: 'sorvete baunilha',
    },
    {
      thumb: './assets/images/desserts/sorveteChoco.jpeg',
      title: 'Sorvete de Chocolate',
      description: 'Sorvete de Chocolate Delicioso',
      price: 7.90,
      tags: 'sorvete chocolate',
    },
    {
      thumb: './assets/images/desserts/sorveteFloco.jpeg',
      title: 'Sorvete de Flocos',
      description: 'Sorvete de Baunilha Delicioso',
      price: 7.90,
      tags: 'sorvete baunilha',
    },
    {
      thumb: './assets/images/desserts/sorveteLaranja.jpg',
      title: 'Sorvete de Laranja',
      description: 'Sorvete de Baunilha Delicioso',
      price: 9.90,
      tags: 'sorvete baunilha',
    },
    {
      thumb: './assets/images/desserts/sorveteManga.jpg',
      title: 'Sorvete de Manga',
      description: 'Sorvete de Manga Delicioso',
      price: 7.90,
      tags: 'sorvete manga',
    },
  ],
};
